import { AlertTriangle, Check, ChevronRight, CircleHelp, LoaderCircle, Lock, Sparkles, X } from 'lucide-react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useFeedback } from '../app/feedback-context'
import { routes } from '../app/routes'
import { useProduct } from '../app/product-context'
import type { CampaignPlan } from '../domain/types'
import { planCampaign } from '../services/aiCampaignService'

export function CampaignStudioPage(){
  const navigate=useNavigate();const{dispatch}=useProduct();const{notify}=useFeedback();const[brief,setBrief]=useState({product:'桂花拿铁',goal:'提升秋季新品认知，并带来可核销的到店消费',audience:'近 90 天到店 2 次以上的咖啡会员',budget:2000});const[plan,setPlan]=useState<CampaignPlan|null>(null);const[loading,setLoading]=useState(false);const[showCompleteness,setShowCompleteness]=useState(false);const[confirming,setConfirming]=useState(false);const[endDate,setEndDate]=useState('');const[term,setTerm]=useState('');const complete=Boolean(endDate&&term);const score=complete?100:92
  async function generate(){setLoading(true);setPlan(await planCampaign(brief));setLoading(false)}
  function create(){if(!plan)return;dispatch({type:'campaign.created',plan:{...plan,endDate,authorizationTerm:term}});setConfirming(false);notify('活动已创建为草稿，未连接外部平台或产生费用');navigate(routes.campaigns)}
  return <div className="studio-page"><header className="studio-header"><div><span>AI 活动工作室</span><h1>把经营目标变成一场可执行的共创活动</h1><p>AI 负责经营方案、平台策略、奖励测算和风险提示，最终决策仍由商家完成。</p></div><div><button className="secondary-button" onClick={()=>notify('活动草稿已保存')}>保存草稿</button><button className="primary-button" disabled={!plan} onClick={()=>setConfirming(true)}>创建活动 <ChevronRight size={16}/></button></div></header><div className="studio-columns"><section className="brief-panel"><div className="assistant-message"><Sparkles/><p>告诉我推广商品、经营目标、人群和预算，我会用同一套增长口径生成方案。</p></div><label>推广商品<input value={brief.product} onChange={e=>setBrief({...brief,product:e.target.value})}/></label><label>经营目标<textarea value={brief.goal} onChange={e=>setBrief({...brief,goal:e.target.value})}/></label><label>目标顾客<textarea value={brief.audience} onChange={e=>setBrief({...brief,audience:e.target.value})}/></label><label>活动预算<div className="money-input"><span>¥</span><input type="number" value={brief.budget} onChange={e=>setBrief({...brief,budget:Number(e.target.value)})}/></div></label><button className="generate-button" disabled={loading} onClick={generate}>{loading?<><LoaderCircle className="spin"/>正在分析经营目标…</>:<><Sparkles/>生成经营方案</>}</button></section>
    <section className={`plan-panel ${plan?'ready':''}`}>{!plan?<div className="empty-plan"><Sparkles/><h2>完整经营方案将在这里生成</h2><p>包括人群、体验问题、平台理由、奖励预算、增长预测、主要风险和策略依据。</p></div>:<><header><button className="completeness" onClick={()=>setShowCompleteness(!showCompleteness)}>方案完整度 {score}% <CircleHelp/></button><h2>{plan.name}</h2><button onClick={()=>notify('方案内容已锁定，后续生成不会覆盖')}><Lock/>锁定方案</button>{showCompleteness&&<aside className="completeness-popover"><strong>完整度如何计算</strong><p>已完成：商品信息、经营目标、目标人群、奖励预算</p><p>待补充：{complete?'无':'活动结束时间、素材授权期限'}</p></aside>}</header><div className="plan-overview"><article><span>活动目标</span><strong>{plan.goal}</strong></article><article><span>推荐共创者</span><strong>{plan.audience}</strong></article><article><span>共创任务</span><strong>{plan.mission}</strong></article></div><div className="plan-grid expanded"><article><span>体验问题</span><ol>{plan.questions.map(q=><li key={q}>{q}</li>)}</ol></article><article><span>平台组合与理由</span>{plan.platforms.map(p=><p key={p}><b>{p}</b> · {plan.platformReasons[p]}</p>)}</article><article><span>奖励规则</span><h3>{plan.reward}</h3></article><article><span>预算分配</span><dl><div><dt>基础奖励</dt><dd>¥{plan.budgetAllocation.base}</dd></div><div><dt>增长奖励</dt><dd>¥{plan.budgetAllocation.growth}</dd></div><div><dt>风险预留</dt><dd>¥{plan.budgetAllocation.reserve}</dd></div></dl></article></div><section className="forecast-strip">{[['预计参与',plan.estimates.participants],['合格内容',plan.estimates.qualified],['朋友领券',plan.estimates.claims],['到店核销',plan.estimates.redemptions]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section><section className="risk-rationale"><div><AlertTriangle/><span><strong>主要风险</strong>{plan.risks.join('；')}</span></div><div><Sparkles/><span><strong>策略依据</strong>{plan.rationale}</span></div></section><div className="completion-fields"><label>活动结束时间<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><label>素材授权期限<select value={term} onChange={e=>setTerm(e.target.value)}><option value="">请选择</option><option>30 天</option><option>90 天</option><option>180 天</option></select></label></div></>}</section></div>
    {confirming&&plan&&<div className="modal-backdrop" onMouseDown={()=>setConfirming(false)}><section className="launch-dialog" role="dialog" aria-modal="true" aria-label="创建活动确认" onMouseDown={e=>e.stopPropagation()}><button className="dialog-close" aria-label="关闭" onClick={()=>setConfirming(false)}><X/></button><span>创建前最终确认</span><h2>{plan.name}</h2><dl><div><dt>目标人群</dt><dd>{plan.audience}</dd></div><div><dt>活动预算</dt><dd>¥{plan.budget.toLocaleString()}</dd></div><div><dt>奖励规则</dt><dd>{plan.reward}</dd></div><div><dt>活动时间</dt><dd>09.15 – {endDate||'待补充'}</dd></div><div><dt>授权期限</dt><dd>{term||'待补充'}</dd></div></dl>{!complete&&<p className="dialog-warning"><AlertTriangle/>仍有信息未补充，活动将以草稿状态创建。</p>}<footer><button className="secondary-button" onClick={()=>setConfirming(false)}>返回修改</button><button className="primary-button" onClick={create}><Check/>确认创建草稿</button></footer></section></div>}
  </div>
}
