import { AlertTriangle, Check, ChevronRight, Filter, Search, SlidersHorizontal, Sparkles, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { assetUrl } from '../app/assets'
import { useFeedback } from '../app/feedback-context'
import { useProduct } from '../app/product-context'
import { PageHeader } from '../components/ui/PageHeader'
import type { Contribution, ReviewStatus } from '../domain/types'

type FilterValue='全部'|ReviewStatus
const reasons=['描述过于夸张','缺少真实体验细节','图片与内容不一致','商业表达不符合规范','其他']
export function ContentCenterPage(){
  const{state,dispatch}=useProduct();const{notify,confirm}=useFeedback();const[searchParams]=useSearchParams();const initialFilter=searchParams.get('filter')==='pending'?'待审核':'全部';const[filter,setFilter]=useState<FilterValue>(initialFilter);const[query,setQuery]=useState('');const[selected,setSelected]=useState<Contribution|null>(null);const[showReturn,setShowReturn]=useState(false);const[reason,setReason]=useState(reasons[0])
  const items=useMemo(()=>state.contributions.filter(item=>(filter==='全部'||item.reviewStatus===filter)&&`${item.customer}${item.title}`.includes(query)),[state.contributions,filter,query])
  function approve(item:Contribution){confirm({title:'确认审核通过？',description:`通过后「${item.title}」将进入可发布状态，并触发基础贡献奖励。`,confirmLabel:'确认通过',onConfirm:()=>{dispatch({type:'contribution.approved',contributionId:item.id,eventId:`approve-${item.id}`});setSelected(null);notify('审核通过，基础贡献奖励已触发')}})}
  function returnItem(){if(!selected)return;dispatch({type:'contribution.revisionRequested',contributionId:selected.id,reason,eventId:`revision-${selected.id}-${reason}`});setSelected(null);setShowReturn(false);notify('已退回修改，原因已发送给共创者')}
  return <div className="page-canvas"><PageHeader title="内容中心" description="同时管理内容审核、素材授权和发布状态，避免混淆当前内容与历史贡献。" action={<button className="secondary-button" onClick={()=>notify('内容规则：真实、具体、可验证，禁止绝对化表达')}><SlidersHorizontal size={16}/>内容规则</button>}/><div className="content-toolbar"><div className="content-tabs" role="tablist" aria-label="内容审核状态">{(['全部','待审核','已通过','待修改'] as FilterValue[]).map(item=><button role="tab" aria-selected={filter===item} className={filter===item?'active':''} onClick={()=>setFilter(item)} key={item}>{item}</button>)}</div><div><label className="search-field"><Search size={16}/><span className="sr-only">搜索内容或顾客</span><input aria-label="搜索内容或顾客" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索内容或顾客"/></label><button className="icon-button" aria-label="筛选说明" onClick={()=>notify('当前可按审核状态和关键词筛选')}><Filter size={17}/></button></div></div>
    <section className="masonry-content upgraded-content">{items.map(item=><article className="content-card" key={item.id}><button className="content-open" aria-label={`查看 ${item.title} 审核详情`} onClick={()=>setSelected(item)}><img src={assetUrl(item.image)} alt={item.title}/></button><div className="content-card__body"><div className="content-card__meta"><span>{item.platform} · {item.customer}</span><b className={`potential-${item.potential}`}>传播潜力 {item.potential}</b></div><h2>{item.title}</h2><div className="triple-status"><span>审核 · {item.reviewStatus}</span><span>授权 · {item.authorizationStatus}</span><span>发布 · {item.publishStatus}</span></div><p>{item.body}</p><dl className="fact-summary"><dt><Sparkles/>AI 提取事实</dt><dd>{item.facts.feeling} · {item.facts.scene}</dd></dl>{item.risk?<aside><AlertTriangle size={15}/><span>{item.risk}</span></aside>:<p className="quality-ok"><Check/>未发现夸张或不可验证表达</p>}<div className="content-card__stats"><span>{item.authorizationScope}</span><strong>{item.publishStatus==='已发布'?`${item.claims} 领券 · ${item.redemptions} 核销`:(item.historicalImpact||'当前内容尚未产生传播数据')}</strong></div><button className="review-entry" onClick={()=>setSelected(item)}>查看审核建议 <ChevronRight/></button></div></article>)}</section>
    {items.length===0&&<div className="empty-state"><Search/><h3>没有符合条件的内容</h3><p>调整筛选条件或关键词后再试。</p></div>}
    {selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><section className="review-dialog" role="dialog" aria-modal="true" aria-label="内容审核详情" onMouseDown={e=>e.stopPropagation()}><button className="dialog-close" aria-label="关闭" onClick={()=>setSelected(null)}><X/></button><header><span>{selected.customer} · {selected.platform}</span><h2>{selected.title}</h2><div className="triple-status"><span>审核 · {selected.reviewStatus}</span><span>授权 · {selected.authorizationStatus}</span><span>发布 · {selected.publishStatus}</span></div></header><div className="review-grid"><img src={assetUrl(selected.image)} alt={selected.title}/><div><section><h3>顾客原始回答</h3><ol>{selected.originalAnswers.map(text=><li key={text}>{text}</li>)}</ol></section><section><h3>AI 生成内容</h3><p>{selected.body}</p></section><section><h3>AI 新增或改写</h3><p>{selected.aiChanges.join('；')}。AI 未新增顾客没有表达的体验事实。</p></section></div></div><div className="review-evidence"><div><span>风险检查</span><strong>{selected.risk||'通过，未发现风险表达'}</strong></div><div><span>授权状态</span><strong>{selected.authorizationStatus} · {selected.authorizationScope} · {selected.authorizationTerm}</strong></div><div><span>AI 审核建议</span><strong>{selected.reviewSuggestion}</strong></div></div>{showReturn?<div className="return-reasons"><h3>选择退回原因</h3>{reasons.map(item=><label key={item}><input type="radio" name="reason" value={item} checked={reason===item} onChange={()=>setReason(item)}/>{item}</label>)}<div><button className="secondary-button" onClick={()=>setShowReturn(false)}>取消</button><button className="primary-button" onClick={returnItem}>确认退回</button></div></div>:<footer><button className="secondary-button" onClick={()=>setShowReturn(true)}>退回修改</button><button className="primary-button" disabled={selected.reviewStatus==='已通过'} onClick={()=>approve(selected)}><Check/>审核通过</button></footer>}</section></div>}
  </div>
}
