import { ArrowUpRight, Award, Search, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { useProduct } from '../app/product-context'
import { PageHeader } from '../components/ui/PageHeader'

export function ContributorsPage() {
  const {state}=useProduct(); const [selected,setSelected]=useState(state.contributors[0])
  return <div className="page-canvas"><PageHeader title="共创者中心" description="识别持续贡献真实内容和实际增长的顾客，建立长期品牌关系。" action={<label className="search-field"><Search size={16}/><input placeholder="搜索共创者"/></label>} /><section className="contributor-hero"><div><Award/><span>高价值共创者</span><h2>{state.contributors.filter(item=>item.redemptions>=10).length} 位</h2><p>过去 30 天持续产出合格内容，并带来至少 5 次有效核销。</p></div><div><Sparkles/><span>复参与率</span><h2>46%</h2><p>完成首次共创的顾客中，有 46% 再次参加了品牌活动。</p></div><div><ArrowUpRight/><span>共创带来复购</span><h2>¥6,820</h2><p>共创者本人及其推荐顾客产生的近 30 日消费。</p></div></section><div className="contributors-layout"><section className="surface contributors-table"><header><h3>全部共创者</h3><span>{state.contributors.length} 位活跃顾客</span></header><table><thead><tr><th>顾客</th><th>等级</th><th>合格内容</th><th>带来核销</th><th>累计奖励</th><th>最近活跃</th></tr></thead><tbody>{state.contributors.map(item=><tr key={item.id} className={selected.id===item.id?'selected':''} onClick={()=>setSelected(item)}><td><i>{item.name[0]}</i><strong>{item.name}</strong></td><td>{item.level}</td><td>{item.qualified}/{item.contributions}</td><td>{item.redemptions}</td><td>¥{item.reward}</td><td>{item.lastActive}</td></tr>)}</tbody></table></section><aside className="surface contributor-profile"><div className="profile-avatar">{selected.name[0]}</div><h2>{selected.name}</h2><span>{selected.level}</span><div className="profile-stats"><div><b>{selected.contributions}</b><small>参与共创</small></div><div><b>{selected.redemptions}</b><small>带来核销</small></div><div><b>¥{selected.reward}</b><small>累计奖励</small></div></div><h3>最近贡献</h3><ol><li><i/>好友完成到店核销 <small>今天 10:18</small></li><li><i/>发布小红书内容 <small>昨天 18:42</small></li><li><i/>获得内容质量奖励 <small>09.12 11:06</small></li></ol></aside></div></div>
}
