import { Check, CheckCircle2, Clock3, Copy, Gift, Info, ShieldCheck } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useFeedback } from '../app/feedback-context'
import { routes } from '../app/routes'
import { useProduct } from '../app/product-context'
import type { ContentDraft, ExperienceFacts, Platform } from '../domain/types'
import { MobileLayout } from '../layouts/MobileLayout'

type Saved={drafts:ContentDraft;platform:Platform;facts:ExperienceFacts;answers:{favorite:string;scene:string;recommend:string}}
const fallback:Saved={platform:'小红书',drafts:{小红书:{title:'被桂花香接住的秋日午后',body:'桂花香很轻，窗边的下午也很舒服。',structure:['标题','体验正文','场景描述','话题标签']},抖音:{title:'15 秒记录桂花香',body:'0–3 秒：门店；3–8 秒：咖啡近景。',structure:['15 秒分镜','镜头时间','画面建议','字幕/口播']},朋友圈:{title:'今天的秋日小确幸',body:'分享一杯舒服的桂花拿铁。',structure:['简短自然文案','图片排序建议','领券入口提示']}},facts:{product:'桂花拿铁',feeling:'桂花香柔和、咖啡口感醇厚',scene:'一个人在窗边、下午阳光',audience:'喜欢咖啡和生活小确幸的朋友'},answers:{favorite:'桂花香很轻',scene:'窗边的下午',recommend:'喜欢咖啡的朋友'}}
export function CustomerPublishPage(){
  const{dispatch}=useProduct();const{notify}=useFeedback();const[consents,setConsents]=useState([true,true,true]);const[submitted,setSubmitted]=useState(false);const[guide,setGuide]=useState(false);const saved=useMemo<Saved>(()=>{try{return JSON.parse(sessionStorage.getItem('cogrow-content-draft')||'null')||fallback}catch{return fallback}},[])
  function submit(){if(!consents.every(Boolean))return;const d=saved.drafts[saved.platform];dispatch({type:'contribution.submitted',eventId:'submit-linyu-current',contribution:{id:'current-linyu',customer:'林小雨',avatar:'林',platform:saved.platform,title:d.title,body:d.body,image:'/assets/customer-moment-v2.png',reviewStatus:'待审核',authorizationStatus:'已授权',publishStatus:'未发布',facts:saved.facts,originalAnswers:Object.values(saved.answers),aiChanges:['整理口语表达','按平台结构重新排版'],authorizationScope:'梧桐咖啡公众号、门店屏幕与本次活动页面',authorizationTerm:'90 天',potential:'高',reviewSuggestion:'事实完整、表达清晰，建议优先审核',claims:0,redemptions:0,createdAt:'刚刚'}});setSubmitted(true)}
  return <MobileLayout backTo={routes.create}><section className="publish-flow"><div className="mobile-progress"><span style={{width:'100%'}}/><b>授权确认</b></div><div className="mobile-body"><header className="mobile-title"><h1>{submitted?'内容已提交审核':'确认内容与授权'}</h1><p>{submitted?'预计 2 小时内完成审核，审核通过后再由你决定如何发布。':'你始终拥有最终确认权和授权撤回权。'}</p></header>
    {!submitted?<><div className="publish-preview"><span>{saved.platform}版本 · AI 辅助整理</span><h2>{saved.drafts[saved.platform].title}</h2><p>{saved.drafts[saved.platform].body}</p></div><section className="authorization-card"><h2><ShieldCheck/>素材授权说明</h2><dl><div><dt>使用渠道</dt><dd>梧桐咖啡公众号、门店屏幕、本次活动页面</dd></div><div><dt>顾客署名</dt><dd>保留“林小雨”的署名</dd></div><div><dt>授权有效期</dt><dd>90 天，到期自动停止使用</dd></div><div><dt>撤回方式</dt><dd>在奖励进度页提交撤回，24 小时内处理</dd></div><div><dt>AI 标识</dt><dd>展示“AI 辅助整理”标识</dd></div></dl></section><div className="consent-box">{['我确认内容来自个人真实消费体验。','我理解并同意以上素材使用范围。','我确认平台内容由 AI 辅助整理，最终内容已经由我确认。'].map((text,index)=><label key={text}><button aria-pressed={consents[index]} className={consents[index]?'checked':''} onClick={()=>setConsents(consents.map((value,i)=>i===index?!value:value))}>{consents[index]&&<Check/>}</button><span>{text}</span></label>)}</div><button className="mobile-primary" disabled={!consents.every(Boolean)} onClick={submit}><Check/>确认内容并授权</button></>:<><section className="publish-success"><CheckCircle2/><div><strong>内容已进入商家审核</strong><p>预计审核时间：2 小时内</p></div></section><section className="reward-progress"><h2>你的奖励进度</h2><ol><li className="done"><Check/><span><strong>真实体验已提交</strong><small>刚刚完成</small></span></li><li><Clock3/><span><strong>基础贡献奖励 ¥20 到店券</strong><small>审核通过并完成授权后发放</small></span></li><li><Gift/><span><strong>增长奖励 10 积分/次</strong><small>朋友通过专属券完成有效核销后追加</small></span></li></ol></section><div className="mobile-double"><button className="mobile-secondary" onClick={()=>notify('内容已复制，可粘贴到你选择的平台')}><Copy/>复制内容</button><button className="mobile-secondary" aria-expanded={guide} onClick={()=>setGuide(!guide)}><Info/>查看发布指引</button></div>{guide&&<section className="publish-guide"><strong>{saved.platform}发布指引</strong><p>复制已确认内容，在对应平台自行发布；发布后可回到奖励进度页登记链接。CoGrow 不会代替你发布。</p></section>}<button className="mobile-primary" onClick={()=>notify('奖励进度已刷新：等待商家审核')}>查看奖励进度</button><Link className="mobile-text-link" to={routes.claim}>预览朋友领券页</Link></>}
    </div></section></MobileLayout>
}
